import lib

int unicodeLowerA() { result.toUnicode() = "a" }

int unicodeUpperA() { result.toUnicode() = "A" }

int priority(string s) {
  result in [1 .. 26] and (result + unicodeLowerA() - 1).toUnicode() = s
  or
  result in [27 .. 52] and (result + unicodeUpperA() - 27).toUnicode() = s
}

module Impl<inStr/0 input> {
  // Split into lines
  string rucksacks(int i) { result = Helpers<input/0>::lines(i) }

  string compartments(int i, int j) {
    exists(string rucksack, int splitPoint |
      rucksack = rucksacks(i) and splitPoint = rucksack.length() / 2
    |
      j = 0 and result = rucksack.prefix(splitPoint)
      or
      j = 1 and result = rucksack.suffix(splitPoint)
    )
  }

  string rucksackGroups(int groupNum, int index) {
    exists(int rucksackNum |
      groupNum = rucksackNum / 3 and
      index = rucksackNum % 3 and
      result = rucksacks(rucksackNum)
    )
  }

  string rucksackElems(int groupNum, int index) {
    rucksackGroups(groupNum, index).charAt(_) = result
  }

  string groupShared(int groupNum) {
    result = rucksackElems(groupNum, 0) and
    result = rucksackElems(groupNum, 1) and
    result = rucksackElems(groupNum, 2)
  }

  string item(int i, int j) { result = compartments(i, j).charAt(_) }

  string shared(int i) { result = item(i, 0) and result = item(i, 1) }

  int rucksackPrority(int i) { result = priority(shared(i)) }

  int groupPrority(int groupNum) { result = priority(groupShared(groupNum)) }

  int totalPrority() { result = sum(int i | | rucksackPrority(i)) }

  int totalGroupPrority() { result = sum(int i | | groupPrority(i)) }
}

select Impl<testInput/0>::totalPrority(), Impl<realInput/0>::totalPrority(),
  Impl<testInput/0>::totalGroupPrority(), Impl<realInput/0>::totalGroupPrority()

string testInput() {
  result =
    "vJrwpWtwJgWrhcsFMMfFFhFp\njqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\nPmmdzqPrVvPwwTWBwg\nwMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\nttgJtRGJQctTZtZT\nCrZsJsPPZsGzwwsLwLmpwMDw"
}

string realInput() {
  result =
    "vvMQnwwvrwWNfrtZJfppmSfJSmSg\nBzGqjlBqBBmztHNFzDHg\nllRCPlTPPqBjPhqhlBRBClhqWcTWrWNcMbQbdrdLccccrnvM\nwMhwbTWpQjbpWHMQppzTHhjtlCjPSSJCCtlqRlJVFJFt\nggdvvnvDgdDmNcBrrcDntFRFqHJJtSJqvlVSRlJq\nfggNNffGmcBrmBfcDzzzpHbsGTpszwwTbp\nBPdPPBggrPtrpbtvPBBdgrFmhhQThGGlbbTZnzZQzZfn\nccjWRJVNcTGmnWWFmh\nDMNmsMHwRNBrggdPDPdt\nTfsfHLQbBtBFQbQsBmPwwlnPGZFwwdwWFZZw\nMRpcvJMJVSMrVMpVSvhhnclwgWwDZgWgWgWglwcG\nGCzjRJjVjSSrvfNQtLmQNsQbjB\nFrSPFjtVvwsqSwcG\nhDHdWDngpgZTDgHzzHwNNqlwNvZJlGqcQGsl\nwDzLTDHgFffLtRft\nCnCJNVqvCBJBNZmfPcPMcFLVcwmd\nHgzjHFghSFtrLfwPchPM\nQDpjgDSQlHHlDQQRzRzsBRRvWnWvJvZnqWBJNF\nmGHcFPFqzPtcfPwDGVVpgLgSlgBl\nrCvddTrnsbDLVSDwjSjd\nQWhWQThswssMQMMMvhTzPqJzmzftHccJfHFhFm\ncPbNpLVFTPbbFrpTLQBzqqmgnnBhgLMM\nvvSwWCZCRZCDZtGwzdgWdQmzqgnQddJn\nvCltGltCGmRRmCvDjjtHFpbcFfbbfssbpNPpHFpH\nWLLQMWZLSPMPWmrwhnjhZZhpHJHljBDB\ncsbtCfFgCftGljHwHcBnpnJR\ntsvgszNtfMwPzWqPrS\nNbDZrbrFQQqqQtQqQDtTcBvCLBLswsZhscCGBZ\nljmWRzVRpbndMWmmfdsTsCBsGwTVVVCGCGws\nffRpnllHRMfdWzdnmRNQNNSFQQFNbrFHHrNH\nLccGzWNjcvNLGTmHNsNLMlMwMpMPGlMCwFwDDGCw\nfZZtfrZgrfQSnnnSnJRCglHpCwwHwpglDClFMw\nSqJQnffJRnfQQVRhrQtrhnThcLhzNzHdTjhsTWzjdmcm\nQJQwJMSbtbRgMQMQVZpCZsrrhpZBwrLLvs\nqCNPGWdqhpphsWrB\nDcNPNnqjdGDqjmPGGJRFMQmgtlQmQJCSgb\nblTRbDnHRGGBwnGPCtFPWzVCDvFWtL\npdSJprqhhZSdqSdZNhVzZWtzLVgVPvzjLzWv\nrrsqsmrMpPHlwTsRHn\nmbNhgbRSLmTwswFm\nvHjHBWMHBzMqWZVZBzHzcwwwdcFLcpLspdzwpwQd\nHfMWMfvjWtZHqWDlhSnnnJNnbhslDb\nlwsvPPnqlwwwsPcHTgqcRcSccmgQ\nCVWBWCFpFzWfFjWjhNSQJJmcVcHRZJNTSc\nzdhfzBtfLLtfFClbrDvsPvtPbnmv\nPntVQbDnQHcDVvhtbtDhcbPcFTrrNfjqmmPTTZqMLZZMjFZm\nlgJCpCFCSCGCpllWMfZqTNNZrMjrJTTM\nCSzSwgFlzsGBzQcQhsnnDbVdtc\nTHzqvrVrWzhqhWwqhTbNNDRtFRmmpFDDVsFLLsdddF\nMbZSSScZSGCJCjZlCjdPmpRmFLDtctdmFRsp\nGfJQlnZjSMnllbJCQbClnZQrhNwwqhBzTNhrffqhqWhTqz\nBdBdmDZHFFbrHHStPSRtPCzSRNDS\nJGGpwqLJGMTLpLlMpqLhJtzCCSGQSPzNNczVVPVzSV\nWwpllfslqfhffLwhfJpJlqlwdBmZnrdFHBFBBmNHFsFmdZmn\njZfQZnZfnbRfjCnfbSSmVpqmNmVpCqlhCqqPpP\nMdJMwMvvLDssLtFMsMtLDsvvDRmmmPhWzWzphpmqDVzPDWNp\nTsLdMrvRtLJtGdtGRRtFTBjSBrScnSZjnbcgQgHfnB\nRZfmlRlWJmWLLRscrslJqvvMdVwmddvPddQPVDdDwz\nGStFbFCbntbjNnjFhFvdHfhzHfzzQdMHwPdD\nBSGpFbbjbNjnNNFSbRsLlWqgrZrfRgsBlg\nztHczmrmcNNzHsPSTwsPHSQPQT\nCFCRjlvbClCjBdPDFQdwBsqn\nllbRgjClJCVVMMCssfmNZWszrNgzGL\nmmFldllVlmtdWFvPPFBcSSBW\nDZzZGzZswQZHwQZjZzWWTSSvjSdvPvvWjJTS\nDpQQggwzZGdmbCldgVgf\nPJJvhqzVGbTFqzqbbGTlLmrtrZMnnZnntlJnrD\nfNwRcQBCRNddNgLtgDnttqrMMtlr\nRfRdNWQHcqHscdfRdGPFbFPpvpVWWzPzVS\nDRgjZRRDggTfjfRvwWzHGGHPWDswvv\ndhbmpcCmchgCpsGzWPdVGvWHwP\nhpMMMpCQMnChFgNRQffTRrSN\ngfqPCHWtPMMjCtffgjQWGLvGdZcdLLGZcLFGZBWG\npJTDsnnnvBjnFwvj\nzJRpTbNrTSppRVblgbljMgMfCfbC\nfGrGwqggtbVmtzbf\nCTMjNQcJjJTBNCjMNZFNBcCZHbmWZHVLZDDWVtDzzbVmlV\nhMvTcNMFMhQjTTBFBNMhwpspwgnGtvtnSgdwrRpG\nRfFdqPdMMGPVgWmNVN\nQwrTsbnSsSQpwlSSbNNWDmGLVjjmLWwNVB\nrpcclTCprmZQSbprSTpRRRfqMfHHCHfhMhvFJM\nLnJJsMtLbzsPPVPJbrTBlTWlfRfqnTrrlr\nVDHVQNFGgNTrSjSBjq\nCHFHGmvDGdZZGCQZVDgDHVbwLLwtMwwmJLJbLPPMbczt\nqNNNBllFBzFjjzwGqGgLrWgrtQjdmmtQmQpp\nZMHJCPhMZRsRCsCPsSJZLmQdQgrtQwQwQZwdWg\nCnMPbbRbsPhCnbfhMPRPllnFGqwTTFzTzNvBGBGc\nwZWlBFZQgBzTzpZwBlVpzWBWnNMmnMvMcMJMmLGnVmqLqGMq\nPdSDfJbCHsHHdJjsRRhjjPjmLqnnrLMLcrnLvdLMNccvGn\ntSJtSCtbJhDhtzlFQZlTZTFp\nTNqZDqmMDZNMFSGHjSGBRBdN\nCrrwVwsPjjBHddPf\nrpWggQVspQWcgtLwcHZZzDDMLDvvnnMzDM\nlWrWmPwmGlZwZjdLZLzV\ncFcDJhJnmqBqDCRpZzVLNsFLjLzdds\nqJchTDCBHDWglmrfWPHH\nRgLRnTJWnfHDcQQBfg\nbZpNwdwbdMvVPsHHJMQfSSfP\nmVbdNNdrbCzZbdZvbWTGrhqjTJtRWttRjq\nTMtqqBJLrwqrZPlHHGhGnlBhzv\nbFgNcpDRnpgggjCzvWDWhQhQWQHHvz\njnnVgjcgcTZMJqJVtT\ndVSjmdHrfGPddrQgstFgzsQfsMFQ\nhvJJCCJDcCtwBVFQzzBD\nRWCnTvWTLRnJJLJllWhTLSprVdNZVGHGNGGnrdGSZH\ngvMSHFZtBBMBMFZHzjnqLsLGMCzRWWMn\nQJmDrhbNDbJfPQhDmQPRLszRlnjCzzWqrRnlsL\nPcJVhJbJJNcNDmfDmjJmbhTfBvpwVSdggtgvgSFZwgvtgpdZ\nPBClRHHClRlFljllZSBBBllppVGDLpZVVVsGpmGcNDpGLL\nMvNwnbMwccVsswDG\nMqnNbzMMrQfnqtttqfQWQQnRdCSHgHPglRFBRWlHjWRlCW\nlldwdfSBWphHBggZghFs\nDjDbDVRzDmLRzRLGJjPssrLZPhdshFHrssTZ\nmvddMzvmmDDvvwQqWftCfqWqfM\ngpTTwNWGWMSMgJjnvpvvJbJppn\nlQvmLFdfrQzRFctlrLdRLVPnhPPbVDPDfjnVbfhJjV\nFLFqccvmmtcQtrmQccRFLlRLSSWBSgTWNwsggqMBsqWGHMNG\nPjPtVQrPVjrVPLLDQVFLTTWWqbSZwRwzqwSbSbbbwFSq\nlBnGJBnfflRRNZwbqb\nHJMGgmfpRMHGGdgncJHLDjjtVDQctLCvQCjTtr\nVvmvjRGwRwvhmhRvvvVCCTTJjfWqfDMMcJlcCD\nNpNbPfpSnngZbbLMFJWTMlLFqJJDMD\nbNSfdSHQZgVQzwhhvRmQ\nMhmHcDhChhcPVMDPDPQdFhQHnbNpZbZnprnrmNnjNbsllbnp\nWWqGCWSCzsGbbGNgjN\nLzwqBLSvwJCLPVMVDLdhMP\nmNVLLffSLVWdZCcFZCZrSbGr\nglvcwszTlsRDrHQCZFCvGH\ngTBRlJnwhzgTgsTnggslsJRTpLNmjmNNcdVLdhfpLpdLVmLc\npCgfDrDrgccfppmDnhHMGqGbpHHSqzGLlqHS\ntFtjQRPFFZRVNRcQGbLzLFMSGzSbWLqH\nQRNTZjvjTTwtwNfmcTgfnCgnnBhm\nhcPBhqPzqWPccHWHHWqnPdssPVfFFmZDnVDDms\nNSLNCTRQZndRmDfnRD\nQSGTGbjTSTJHBlbZZBbh\ndgcWgVgWdvZSbbRtjLRZZZ\nMMDPPfTnPTQrFDMpHzmmLztLnsszRtwbtS\nrDfDqfHTpCSJqlCCGq\nbjsgllstBbpNpslBpdBgqljgGwzJzDzwLGGrwLQQdJDwGhQh\nnncmnmHHnmWRWmPfJCnvPRMrzvDhZZLGQwhDLhhMzZZZ\nmffccVHRRPTTNlpNbNjJVslJ\nDgPstgPtgPNNcjQQrtPJJCRSZTwSGJZZCZCJGD\ndHVvpzdBBhVqzWqvhvHdzGSZlTRCSRJrwSSCwJCWGT\nzpvVVqMBrzqrhFBvjbNPcPLnjcQtMcnj\ngBcmTCFghhCCBnBhWWwFbwLdwHFMLMdp\nLVzlZzPPMMzWWrwH\nljqjsGlZPPqqlVsPqDVqjQQctNTnRcNLtCNmmnRTRthBGG\nLPRrrBNNjLBRJNdrGPRBfBrLwFqmDbdbTbTgmmgwmttFwtmH\nQQcVvnQphlWsCQCCVpnvptTJgbtqwHDwbJtJHFsTHw\nppcJVQvpvMVMCvQZQVVZCCSRZPSjNRRZBPPPPzLjSLGf\nMLtRnjQsRMJcDQJnSrsfqVVvGwbbbqgggg\nWBFCNlFFFhFBlCHbplFWdpWZfVqPPwqTGdqTGvwrPVvTqvTr\nHClCHzFzFBhmnjtQzMMSMnbD\nsVnMCsdlMRcMFBGz\nJvwwgrJDfgDmmggQrhNfhQQftjFrGRRtZFGBRZFHzjGcjrcj\nPBJJvgDPNllPddVCPl\nfmmRSnfnMnFSmMmmzTDSBFHtlJJqHJJqdHQdTCdtCCdt\nWggGpNVVgWdwwHQtlGlC\nhjbWppbLbLZLjVPPjPLSRRMvDlmSzDzBSnBFZf\nnVttMPnPLjnJLjcnPVCjJJLcssfggBNlffgcNsWTcGcgNsBF\nHQbwhmDrRrgFsWlQGNls\npZdbGzGrGpVttPLttv\nLLbMrMHLDdWhmgbqqt\njGSQZQTpQGVVRSlQMQRljZmgmJBSvggvBWhJmJWvddmt\nVjlQFGMVrFFrDrPw\nDZVDwGZlJlVlwZVDzNdqfjMDnjqzNnWf\npmtpLRQFhSFpmpRgRtHNFznNdqWBjzWfnBjMWf\nrHRrhStppHdJcGJrrssCsV\npgQqHwgPcPCddCjdWtdp\nVfZGVFfNVhZhzjjjLz\nfNNBBnGVNfBfRSRjBRQHJQTwJcJTgHPwTngr\nMZdlzWzthMgrwmGmqZNqNs\nVvJQJPVDBJQThwwNsRqsvRsHHm\nBDQQPTnDDBQQBVfTBQPdFctzzdtztMMtnhcWcd\nLjWjDShflZRRcZzfHH\nsrNwQPBsrVRhNmRGHzmM\nrBdgQTrhdPndQTrsQQsrPwnTpLLCWDpSCLtCnvtSWpJjDCvl\ngSlvDwCvcmcTQTFtRMjWHFVVHwtj\nrbsphZZzBshGZssMffTVRFfFpWpfTH\nGZNhZBhPBzTPNLDcDlCDCJNmlg\nsmZjGfvjbWWffQtf\ndwRrdlVdDdgDbNtgcgQSNStQ\nFdFVwdblFlzVrlwrTlndZHHZGhmLhhssjHhMjnjq\nQFvQVFLLgVrFLBVgGhTtllPvmHRRGbTm\nhDCCNCNCJNzWDZnqJDzSNCTnbRttHGRnccbPRtmmlmHc\nqJshNMCNdVFVfsLB\nFcLZZPFjdZcZMPcRjcRTgbpJlwbbTlmdTlGlwD\nnrrNrHWBNSWvBqvvrhBqzStrgGnnmbwsbbJbwwJnmwmgJTlD\nBCrrNvqWvSQPcCGZZRQQ\nvPwcJblJzJbJcJFcwBSvJNdWRLtdsddGWWddWRWsMF\nmDZmmDZDHVhfmjZgjVDfhTZHtsNptRsMntnWdsMnGtRntG\nmhQrQDDhgqTTNfhmVQVBrPlBczSJbbCbCCPPvb\nZjbjLlbZjGqsgJTfHggrVvlB\ntFDRFRnMFnnWtDdMdDRhzHfTJhJhffHvHTBHTgcfJV\nnztDtdWzCCMSptSdFRRswZjsLbjwZmwqwGqpQV\nvnvmmVnmVbrBJlzgWQWVNFzNHV\nMwSjZhSwPjMwfDRzgWlNpWvHlgNNNP\nCfSZjSfftwZDChDRSnccnrvBbbGrtBvctr\nLCBRQRBQwRrCVLVWSrCSwCptzvhthvGGhdHzwppTTddv\nmFnJJmnmFFFfPLNNmqqNJDpGnGtbHTtHvhnHbzvHvpGv\nlMMPLqDmNMVSjjgMCS\nzzPzbLjHLjfQPQHwwjddFNsNSJjDMsdNMFsC\nBqqtmgDhcqdSFCdsqddF\nGtcmrvhgcZlvZtBhtVgrvrvtnWzDnQbfnwlfWWRHWbbwzHRL\nJfWHWZcMMdDLMPjRnCJjRbFgnblF\nShtBTSmBhTtqtfmqSTNvmjVjnFbFnnlrlqgCnrFnVg\nvfzTTthppmdzPLHLWdGZ\ntdvrvGgGTSScnHcjcg\nzLLVfzPPcDZnPjSPpD\nLfffNFLNlNbJwrctthWqNdNq\nNdjJtfVNZnnFFdtfGfFNcvpbMDbzdcTbbzpvmcDR\nPHMSHCHHWrRCvzDzDChT\nBqPWSHwllSQWrLHQHPqlBBNfttZMjFQfjGtZtNjJJjnN\nCpZtMCMQQpCVWjMDVjPVQsWWqJJhbTcddPlfhTRqchcJblhh\nNwDSGNmGRccqNJfT\nSBSSmgrrgGHnvSzwGVWDCzMCpLZtMsstLM\nsbjHQsBlBQrrGjQjBqCRSnSCpnfngLnFhJngFfSP\nzHVctHDcZtdJffnPpcSpFn\nZdwNMztdvzVdrqblvWsqHvBR\njPdjFPSbVDMMbqZzQWzQ\nhFRrJlpprGhtlJGQzmCRmZBWQCHRQR\nvThNplJpNhltNNlvcGDvwVFgnPwvSgPSSfjS\nDhDTPQpTDmQbDQrrrWtWPJNNrrsJ\nqqGjgwCgVRjMSRwMMGRGqjwvsNJJBZtrstvNBvHWHJvL\nVqqgfjzfgfFGVjRggCGznhlbTpQchcshpdFlnDbn\nDpTQTBbCZQVJQZJjrFllGdlvMPlMLqGBGvLl\nhmnWHWWNzzmHsmWRlGGpdLgLHGlqvgqg\nRzcWRhRnRnfmswfwtzzRWrDTrrFCQTCpQpcCrjjQCp\nHLvpHvGcBTDFznvfqT\nhCPQbPZPbjSbwwjCPChSClJJfzqTggTFDfsJngDg\nStqmmZbdqrQmhQrrhZWcRcGBpBHWVcLctMWp\ndNnRNbRdbRJMBMBVVThn\nrNrsLNscFsCDjpwTMgBGWMGjJjWBVJ\nwNcLpqHNsCprsfLFsHwRvPSSPRZRtRQSqtQPmP\nPPhGfbthhBDVsTDtDqRR\nmCmSNmqpcqjjrCScWRsZDpHsDQRZQDZDss\nCcWzNmccrjjvqBGzzdPGnv\nSDRmCSFfcSFFcfDmDBFSCfdVJhpzZjNJTNzRTvjzjhzNjTtZ\nngGsltrMWrblNpNTJJplJN\nPGGnGsWngrGLQHHtHHHgWsHSBLqqfLcqBdVdcCDDBFdCDm\nVPjGwhwVPhrnqhzJmQvQTQvmzBzw\nZBDBRbLLdtfRLlddLlCLCZMgmFJQFDcvzMQmgMzzJJFJ\nLHLWltHlRZCtBVhVVHPjGSpphp\nJqhlhdnnmfRVVSpzWLjzVLGpvB\nstQtFTTrsZQPFQNNDtQgLzzSLvjvLGLBGSZGGWJv\nDDDFFgDPbTwbTTJMCMcbCqqmmRRCnb\nJbDWPDPPJJDMDjHPZHGbHGVZTBhrzBpdzszdTTphdNdWdrpv\nRmRRqllqffwFtqwLCsqTNvpCsqCNqvdN\nfmfLmStlnnfnRtfcnQbbjPjPPggZGVsMQMbb\nWJggvGDJSwWgSfgvfSMGqqQHBcPjcHChcQBCssDHCTTQ\nmlRnbrnbnltblwdnnpbLRdCCjCTHTjPTTsQcTrHHhCcj\nbFLbdmzRpvSwfFFNWN\nBHnDnQHnHMWLwzWPzD\ndmlZCrdqLZzZVZJM\ntRRtdlLCjLmqCRsrSLrvvRQNFQnbgRTQQNHTBbGQQh\nZrQPQWCrJnPdQSNTmBJNTHGHJN\nzhFRfswjwhhsFttfsfvQftRtLTzmBTHGTBmzMLHHLmGHNTTS\nhQhwqVjQwsdggrZZCWVl\nVjfnQgVQjblChfjVJlbzLtrSLlTGtztHTtsTGH\nDDqWQDQMWmDwWNwcqdWvpSrtLpLsptMprMStstMz\nvQcddRdRvWcwWRmmmmddZmmfVnnngJJbZnCBnBhhFbhCgJ\ngVgDnnmJdQVdJJgtgDjBsBhsBSPRSRRSSwccSbSqwPcCPcSC\nHrQHlHFpQfTHzzWzwScPPCRfLbPSfCSR\nTTQlZNTzlZNMWvrZMlpnhnVtnDDnVNtVJnjmhg\nMCmmssFnZJcNNszfpvvrpvJzvwpp\nBRRRWQWbSRGGRTTtZHWSqTrvDfgfdfrrwrDgfbvfzfrd\njRBhWRWTSRttQBZMNchNCsmFMchP\nGBDncllqcSlNFZWBFWPjHVbw\nLQphJlJzLCwPjHbpHZvV\nhzCMJLMzTsrdrszQCCCTCQCDlqqnNmggqfGmgdmGgcmSNt\nhFVVbqJsqhcnBRTRGBTh\nlwdDpmzdNznzZBgGRRjR\nHdmvNvSCmDmwNDFrMJMqJFCRfsbq\nctnbTcFTnbwSSfrrMLRhpJLMRdpwdJJR\nvdGCVBmGVHPLBRWhpRLJJZ\nVmQPHqvsPdlQsVHDftnlFTbffnbttfTF\nLBJZHrhLThHddcMLVtcMcL\nCPMNFDDMpGqFjjSPDPDqdvmdtQgVQQcQWcQgQQsj\nDzFDFMRSFPSGTJJTJBwwRhBw\ndpldqlqlRppFTHpbjbnLRLVnnGfjtG\nNNJTcmhzvJQNgMJBwcGtjtGbttfhtsGGnhnt\nrzcwmgvcvrBNvvmMgvcBzwHPCTWWprqPHqTFWdPCWDTF\nBNllDRTNqDNvNDDLBcDvBCLVJrVdJdtrnrCHggtrdd\nmppFMFjpMFZQZQGjFCdgrCrCdrvVGtJJCC\nPZsQmfPphvPjSsjmPjfZllBwcNRDNcDqNNWbTclS\nfjqZBSDSDwwsQwCDND\nrrdMdjVWtTTPslsslFLTLCsJ\nrvPWbvcmHjmdPbHvrvBHgqRRgqHGgfZGfHRS\nggTQgsgwFrTrggbMTvSdmjfCmmQDcmqjDjmc\nnLZnRhNZnnNHZhZVStCcDqjcqmjSjH\nRWGNnhzBnJJRRWNRBNZNLZhFMTFPvrTrTlsggPwSlFMWTw\nRNmnPRnLGcQmzBQpHHjTltjtlfgspbsq\nCZvCJwZMMCCMdFVcwJJsgTTHfsTlbfbgbT\nSSVFhWCZdSCcWCcWdrvhzmnnnLNGDRDNzzLNGz\njPwfPwNfFpFNQpDjdMcjcrdddDHD\ntzsRsGRLzhLhvqvhHMlqqV\nLRBnRBGSnBSGsGSGmGtBJCmnNWZpPpTNPMwQMPNJFZTTNwWT\nPCrStRPSPvZQcZPvqvfjSRWFFNFJFLZTTJTTVZFFGLFF\nDlpBzBntHDzhlpGJVHLwTMFLVLTL\ngptBBdgzpsBbpQvvPQPRqrdcCC"
}
